### ISSUE TITLE
Where is the dataset folder？

### ISSUE THREAD

**Issue by xmBryant24** [LAMDA-RL/ODIS#1]
Hello, your source code does not include the **dataset** folder, do I need to create a new **dataset** folder under the **src** folder and put the offline data in it?

**Comment by mansicer** [comment]
Hi, there! We have a `dataset` folder located in the root directory of this repo. However, in the previous version it is filtered by the `.gitignore` rules. We have modified these parts and you can pull or re-clone the repo for updates. Sorry for the inconvenience. Have a good day!

**Comment by xmBryant24** [comment]
> 
Thank you very much, the problem has been solved, your project and methodology are fantastic
