### ISSUE TITLE
NaN during Cooperative Navigation Tasks

### ISSUE THREAD

**Issue by euikk** [LAMDA-RL/ODIS#4]
Hello, I have an NaN issue while running Cooperative Navigation Tasks

NaN occurs during train_vae. 
I just change following setting:

- skill_dim: 4 (originally 3)
- attn_embed_dim: 64 (originally 8)

Is it just a setting issue? then please let me know the settings you used for the ICLR paper.
(other baselines work well) 

Thanks!

**Comment by mansicer** [comment]
I ran the experiment in my machine and didn't find the nan issue. Here is the command:

```bash
python src/main.py --mto --config=odis --env-config=cn_offline --task-config=cn-expert --t_max=30000 --entity_embed_dim=32 --attn_embed_dim=64 --skill_dim=4 --seed=1
```

Maybe you can check

1. if you have updated to the latest code via `git pull` (I fixed some wrong datasets in recent few commits)
2. whether the versions of torch, numpy, and others correspond to the requirements.

**Comment by euikk** [comment]
Thank you. Till now, it works well.


I have several questions.

1. In your ICLR 2023 paper table 6, the hyper-parameter 'attention dimension' is 64. Does it mean that 'attn_embed_dim' is 64? (in your code, it is 8 originally)

2. I think NaN is because of entitiy_embed_dim. Then for MPE, the settings below are what you use for paper?

- skill_dim=4
- attn_embed_dim=64
- entity_embed_dim=32


Thanks again.

**Comment by mansicer** [comment]
The attention dimension in the paper refers to `entitiy_embed_dim`. `attn_embed_dim` keeps 8 in our experiments, which is exactly the same if you run the command in our readme. Actually `attn_embed_dim` is the dimension of attention in our state encoder and irrelevant to the final policy, so we don't pay too much attention to it. Sorry for the late reply.

**Comment by euikk** [comment]
Thanks.

Sorry for bothering. This is my last question.
What is the skill_dim you used for cooperative navigation tasks in your paper?

**Comment by mansicer** [comment]
I'm willing to answer your problems so it's fine. We use the default (i.e., 3) in our config. We don't cherry-pick the hyper-parameter for cooperative navigation so I cannot tell which number can be better.

**Comment by euikk** [comment]
Thanks again. Your work inspires my project a lot. I'll close this issue.
